development:
  adapter: postgresql
  encoding: unicode
  database: manga_development
  pool: 5
  username: senpai
  password: arigato

test:
  adapter: postgresql
  encoding: unicode
  database: manga_test
  pool: 5
  username: senpai
  password: arigato
